apiVersion: v1
kind: PersistentVolume
metadata:
  name: volumen2-pv
  labels:
    type: local
spec:
  storageClassName: vol-poisons
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/app/poisons"