apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: local
  name: volumen2-pv-claim
spec:
  storageClassName: vol-poisons
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M